SELECT TOP (1000) [Id]
      ,[Title]
      ,[Address]
      ,[Description]
      ,[ImageUrl]
      ,[PricePerMonth]
      ,[CategoryId]
      ,[OwnerId]
  FROM [HouseRentingDb].[dbo].[Houses]